# Generated by Django 6.0.5 on 2026-08-13 22:45

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('profile_photo', models.CharField(blank=True, default='', max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_onboarding', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_user_email_case_insensitive'), models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), condition=models.Q(('nickname', ''), _negated=True), name='unique_user_nickname_case_insensitive_when_present')],
            },
        ),
    ]
