# Generated by Django 6.0.5 on 2026-06-19 14:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), condition=models.Q(('nickname', ''), _negated=True), name='unique_user_nickname_case_insensitive_when_present'),
        ),
    ]
