export enum PaydayWarningType {
  NEGATIVE_LEFT_OVER = 'NEGATIVE_LEFT_OVER',
  IMPORTANT_PAYMENT_MISSED_OR_UNDERPAID = 'IMPORTANT_PAYMENT_MISSED_OR_UNDERPAID',
  IMPORTANT_EXPENSE_AFFECTED = 'IMPORTANT_EXPENSE_AFFECTED',
  WARNING_THRESHOLD_CROSSED = 'WARNING_THRESHOLD_CROSSED',
}

export enum PaydayWarningSeverity {
  WARNING = 'WARNING',
  DANGER = 'DANGER',
}
