# Generated by Django 6.0.5 on 2026-06-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_per_pay_period_cents', models.IntegerField(default=0)),
                ('pay_period_type', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='', max_length=20)),
                ('debts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_or_mortgage_cents', models.IntegerField(default=0)),
                ('water_cents', models.IntegerField(default=0)),
                ('electricity_cents', models.IntegerField(default=0)),
                ('food_cents', models.IntegerField(default=0)),
                ('internet_cents', models.IntegerField(default=0)),
                ('phone_cents', models.IntegerField(default=0)),
                ('car_payment_cents', models.IntegerField(default=0)),
                ('insurance_cents', models.IntegerField(default=0)),
                ('misc_expenses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expense', to='debt_profile.debtprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_payment_cents', models.IntegerField(default=0)),
                ('spending_payment_percentage_basis_points', models.IntegerField(default=0)),
                ('plan_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='debt_profile.debtprofile')),
            ],
        ),
    ]
