# Generated by Django 6.0.5 on 2026-08-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_per_pay_period_cents', models.PositiveIntegerField(default=0)),
                ('pay_period_type', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='', max_length=20)),
                ('debts', models.JSONField(default=list)),
                ('next_pay_date', models.DateField(blank=True, null=True)),
                ('left_over_warning_amount_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_payment_cents', models.PositiveIntegerField(default=0)),
                ('spending_payment_percentage_basis_points', models.PositiveIntegerField(default=0)),
                ('plan_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='debt_profile.debtprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=150)),
                ('timing', models.CharField(choices=[('EVERY_PAYCHECK', 'On every paycheck'), ('PAYCHECK_POSITION', 'On a paycheck position'), ('DAY_OF_MONTH', 'On a specific day of the month')], max_length=20)),
                ('paycheck_position', models.CharField(blank=True, choices=[('FIRST', 'First paycheck'), ('SECOND', 'Second paycheck'), ('THIRD', 'Third paycheck'), ('FOURTH', 'Fourth paycheck'), ('LAST', 'Last paycheck')], default='', max_length=10)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('auto_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payment_schedules', to='debt_profile.debtprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('debt_profile', 'source_key'), name='unique_expense_payment_schedule_source'), models.CheckConstraint(condition=models.Q(models.Q(('auto_deducted', False), ('day_of_month__isnull', True), ('paycheck_position', ''), ('timing', 'EVERY_PAYCHECK')), models.Q(('auto_deducted', False), ('day_of_month__isnull', True), ('paycheck_position__gt', ''), ('timing', 'PAYCHECK_POSITION')), models.Q(('day_of_month__gte', 1), ('day_of_month__isnull', False), ('day_of_month__lte', 31), ('timing', 'DAY_OF_MONTH')), _connector='OR'), name='expense_payment_schedule_timing_fields_valid')],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('RENT_OR_MORTGAGE', 'Rent or mortgage'), ('UTILITIES', 'Utilities'), ('FOOD', 'Food'), ('INTERNET', 'Internet'), ('PHONE', 'Phone'), ('CAR_PAYMENT', 'Car payment'), ('INSURANCE', 'Insurance'), ('MISC', 'Other')], max_length=30)),
                ('label', models.CharField(max_length=150)),
                ('amount_cents', models.PositiveIntegerField()),
                ('utility_type', models.CharField(blank=True, choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('WATER_AND_ELECTRICITY', 'Water + electricity'), ('UTILITIES', 'Utilities'), ('CUSTOM', 'Custom')], default='', max_length=30)),
                ('includes_internet', models.BooleanField(default=False)),
                ('includes_cable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='debt_profile.debtprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('debt_profile', 'source_key'), name='unique_recurring_expense_source_per_profile'), models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='recurring_expense_amount_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('category', 'UTILITIES'), ('utility_type__gt', '')), models.Q(('category', 'UTILITIES'), _negated=True), _connector='OR'), name='utility_expense_requires_type'), models.CheckConstraint(condition=models.Q(models.Q(('utility_type', 'CUSTOM'), _negated=True), ('label__gt', ''), _connector='OR'), name='custom_utility_requires_label'), models.CheckConstraint(condition=models.Q(('category', 'UTILITIES'), models.Q(('includes_cable', False), ('includes_internet', False), ('utility_type', '')), _connector='OR'), name='included_services_belong_to_utilities')],
            },
        ),
        migrations.CreateModel(
            name='RequiredExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_expenses', to='debt_profile.debtprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('debt_profile', 'source_key'), name='unique_required_expense_source_per_debt_profile')],
            },
        ),
    ]
