# Generated by Django 6.0.5 on 2026-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtprofile',
            name='income_per_pay_period_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='car_payment_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='electricity_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='food_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='insurance_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='internet_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='phone_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='rent_or_mortgage_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='water_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='extra_payment_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='spending_payment_percentage_basis_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
