# Generated by Django 6.0.5 on 2026-06-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_profile', '0002_positive_integer_cents_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtprofile',
            name='left_over_warning_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RequiredExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_expenses', to='debt_profile.debtprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('debt_profile', 'source_key'), name='unique_required_expense_source_per_debt_profile')],
            },
        ),
    ]
