# Generated by Django 6.0.5 on 2026-08-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_period_type', models.CharField(max_length=20)),
                ('income_per_pay_period_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetPayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('pay_date', models.DateField()),
                ('pay_cheque_cents', models.PositiveIntegerField()),
                ('pay_cheque_is_manual', models.BooleanField(default=False)),
                ('carried_left_over_cents', models.IntegerField(default=0)),
                ('carried_left_over_is_manual', models.BooleanField(default=False)),
                ('total_available_cents', models.IntegerField()),
                ('total_available_is_manual', models.BooleanField(default=False)),
                ('total_bills_cents', models.IntegerField(default=0)),
                ('total_bills_is_manual', models.BooleanField(default=False)),
                ('left_over_cents', models.IntegerField()),
                ('left_over_is_manual', models.BooleanField(default=False)),
                ('has_negative_left_over', models.BooleanField(default=False)),
                ('is_below_warning_threshold', models.BooleanField(default=False)),
                ('has_deferred_items', models.BooleanField(default=False)),
                ('has_deferred_important_expenses', models.BooleanField(default=False)),
                ('affects_important_expenses', models.BooleanField(default=False)),
                ('has_missed_important_expenses', models.BooleanField(default=False)),
                ('payday_reconciliation_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('REVIEWED', 'Reviewed'), ('INCOMPLETE', 'Incomplete')], default='NOT_STARTED', max_length=20)),
                ('actual_pay_cheque_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('pay_cheque_review_status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('CONFIRMED', 'Confirmed'), ('UNKNOWN', 'Unknown')], default='UNREVIEWED', max_length=20)),
                ('pay_cheque_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('payday_reconciliation_started_at', models.DateTimeField(blank=True, null=True)),
                ('payday_reconciliation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_periods', to='budget.budgetplan')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('rent_or_mortgage', 'Rent or Mortgage'), ('debt', 'Debt'), ('standard_expense', 'Standard Monthly Expense'), ('misc_expense', 'Miscellaneous Monthly Expense'), ('manual_expense', 'Manual Expense')], max_length=30)),
                ('source_key', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('amount_cents', models.IntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_split', models.BooleanField(default=False)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('is_auto_deducted', models.BooleanField(default=False)),
                ('funded_amount_cents', models.PositiveIntegerField(default=0)),
                ('shortfall_cents', models.PositiveIntegerField(default=0)),
                ('payment_review_status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('PAID', 'Paid'), ('NOT_PAID', 'Not paid'), ('UNKNOWN', 'Unknown'), ('SCHEDULED', 'Scheduled')], default='UNREVIEWED', max_length=20)),
                ('actual_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('payment_timing', models.CharField(blank=True, choices=[('EVERY_PAYCHECK', 'On every paycheck'), ('PAYCHECK_POSITION', 'On a paycheck position'), ('DAY_OF_MONTH', 'On a specific day of the month')], default='', max_length=20)),
                ('paycheck_position', models.CharField(blank=True, choices=[('FIRST', 'First paycheck'), ('SECOND', 'Second paycheck'), ('THIRD', 'Third paycheck'), ('FOURTH', 'Fourth paycheck'), ('LAST', 'Last paycheck')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget.budgetpayperiod')),
            ],
            options={
                'indexes': [models.Index(fields=['pay_period', 'display_order'], name='budget_budg_pay_per_13675c_idx')],
                'constraints': [models.UniqueConstraint(fields=('pay_period', 'source_key'), name='unique_budget_line_item_source_per_period'), models.CheckConstraint(condition=models.Q(models.Q(('actual_amount_cents__isnull', False), ('payment_review_status', 'PAID'), ('scheduled_amount_cents__isnull', True)), models.Q(('actual_amount_cents', 0), ('payment_review_status', 'NOT_PAID'), ('scheduled_amount_cents__isnull', True)), models.Q(('actual_amount_cents__isnull', True), ('payment_review_status__in', ['UNKNOWN', 'UNREVIEWED']), ('scheduled_amount_cents__isnull', True)), models.Q(('actual_amount_cents__isnull', True), ('expected_payment_date__isnull', False), ('payment_review_status', 'SCHEDULED'), ('payment_timing', 'DAY_OF_MONTH'), ('scheduled_amount_cents__isnull', False)), _connector='OR'), name='budget_line_item_actual_matches_review_status'), models.CheckConstraint(condition=models.Q(('actual_amount_cents__isnull', True), ('actual_amount_cents__gte', 0), _connector='OR'), name='budget_line_item_actual_non_negative'), models.CheckConstraint(condition=models.Q(('scheduled_amount_cents__isnull', True), ('scheduled_amount_cents__gte', 0), _connector='OR'), name='budget_line_item_scheduled_non_negative'), models.CheckConstraint(condition=models.Q(('funded_amount_cents__gte', 0)), name='budget_line_item_funded_non_negative'), models.CheckConstraint(condition=models.Q(('shortfall_cents__gte', 0)), name='budget_line_item_shortfall_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='BudgetDebtBalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('review_status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('CONFIRMED', 'Confirmed'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('actual_balance_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_balance_records', to='budget.budgetpayperiod')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pay_period', 'source_key'), name='unique_budget_debt_balance_per_period_source'), models.CheckConstraint(condition=models.Q(models.Q(('actual_balance_cents__isnull', False), ('review_status', 'CONFIRMED')), models.Q(('actual_balance_cents__isnull', True), ('review_status', 'UNKNOWN')), _connector='OR'), name='budget_debt_balance_actual_matches_review_status'), models.CheckConstraint(condition=models.Q(('actual_balance_cents__isnull', True), ('actual_balance_cents__gte', 0), _connector='OR'), name='budget_debt_balance_actual_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='budgetpayperiod',
            index=models.Index(fields=['plan', 'sequence'], name='budget_budg_plan_id_8b403c_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetpayperiod',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence'), name='unique_budget_pay_period_sequence_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='budgetpayperiod',
            constraint=models.UniqueConstraint(fields=('plan', 'pay_date'), name='unique_budget_pay_period_date_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='budgetpayperiod',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 0)), name='budget_pay_period_sequence_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='budgetpayperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_pay_cheque_cents__isnull', False), ('pay_cheque_review_status', 'CONFIRMED')), models.Q(('actual_pay_cheque_cents__isnull', True), ('pay_cheque_review_status__in', ['UNKNOWN', 'UNREVIEWED'])), _connector='OR'), name='budget_pay_period_actual_pay_matches_review_status'),
        ),
        migrations.AddConstraint(
            model_name='budgetpayperiod',
            constraint=models.CheckConstraint(condition=models.Q(('actual_pay_cheque_cents__isnull', True), ('actual_pay_cheque_cents__gte', 0), _connector='OR'), name='budget_pay_period_actual_pay_non_negative'),
        ),
    ]
